export let keyboardKeysEnglish = [
    [ {keycode: 'Backquote', char: '\`', shift: '\~', alternative: '\~'},
    {keycode: 'Digit1', char: '1', shift: '!'},
    {keycode: 'Digit2', char: '2', shift: '@'},
    {keycode: 'Digit3', char: '3', shift: '#'},
    {keycode: 'Digit4', char: '4', shift: '$'},
    {keycode: 'Digit5', char: '5', shift: '%'},
    {keycode: 'Digit6', char: '6', shift: '^'}, 
    {keycode: 'Digit7', char: '7', shift: '&'}, 
    {keycode: 'Digit8', char: '8', shift: '*'}, 
    {keycode: 'Digit9', char: '9', shift: '('}, 
    {keycode: 'Digit0', char: '0', shift: ')'}, 
    {keycode: 'Minus', char: '-', shift: '_'}, 
    {keycode: 'Equal', char: '=', shift: '+'}, 
    {keycode: 'Backspace', char: 'Backspace', shift: 'Backspace'}, ],
    [ {keycode: 'Tab', char: 'Tab', shift: 'Tab'},
    {keycode: 'KeyQ', char: 'q', shift: 'Q'},
    {keycode: 'KeyW', char: 'w', shift: 'W'},
    {keycode: 'KeyE', char: 'e', shift: 'E'},
    {keycode: 'KeyR', char: 'r', shift: 'R'},
    {keycode: 'KeyT', char: 't', shift: 'T'},
    {keycode: 'KeyY', char: 'y', shift: 'Y'},
    {keycode: 'KeyU', char: 'u', shift: 'U'},
    {keycode: 'KeyI', char: 'i', shift: 'I'},
    {keycode: 'KeyO', char: 'o', shift: 'O'},
    {keycode: 'KeyP', char: 'p', shift: 'P'},
    {keycode: 'BracketLeft', char: '[', shift: '['},
    {keycode: 'BracketRight', char: ']', shift: ']'},
    {keycode: 'Backslash', char: '\\', shift: '\\'}, 
    {keycode: 'Delete', char: 'Del', shift: 'Del'},],
    [ {keycode: 'CapsLock', char: 'caps lock', shift: 'caps lock'},
    {keycode: 'KeyA', char: 'a', shift: 'A'},
    {keycode: 'KeyS', char: 's', shift: 'S'},
    {keycode: 'KeyD', char: 'd', shift: 'D'},
    {keycode: 'KeyF', char: 'f', shift: 'F'},
    {keycode: 'KeyG', char: 'g', shift: 'G'},
    {keycode: 'KeyH', char: 'h', shift: 'H'}, 
    {keycode: 'KeyJ', char: 'j', shift: 'J'}, 
    {keycode: 'KeyK', char: 'k', shift: 'K'}, 
    {keycode: 'KeyL', char: 'l', shift: 'L'}, 
    {keycode: 'Semicolon', char: ';', shift: ':'}, 
    {keycode: 'Quote', char: '\'', shift: '\"'}, 
    {keycode: 'Enter', char: 'enter', shift: 'enter'}, ],
    [ {keycode: 'ShiftLeft', char: 'Shift', shift: 'Shift'},
    {keycode: 'Backslash', char: '\\', shift: '\\'},
    {keycode: 'KeyZ', char: 'z', shift: 'Z'},
    {keycode: 'KeyX', char: 'x', shift: 'X'},
    {keycode: 'KeyC', char: 'c', shift: 'C'},
    {keycode: 'KeyV', char: 'v', shift: 'V'},
    {keycode: 'KeyB', char: 'b', shift: 'B'},
    {keycode: 'KeyN', char: 'n', shift: 'N'}, 
    {keycode: 'KeyM', char: 'm', shift: 'M'}, 
    {keycode: 'Comma', char: ',', shift: '<'}, 
    {keycode: 'Period', char: '.', shift: '>'}, 
    {keycode: 'Slash', char: '/', shift: '?'}, 
    {keycode: 'ArrowUp', char: '|', shift: '|'}, 
    {keycode: 'ShiftRight', char: 'Shift', shift: 'Shift'}, ],
    [ {keycode: 'ControlLeft', char: 'Ctrl', shift: 'Ctrl'},
    {keycode: 'MetaLeft', char: 'Win', shift: 'Win'},
    {keycode: 'AltLeft', char: 'Alt', shift: 'Alt'},
    {keycode: 'Space', char: '\ ', shift: '\ '},
    {keycode: 'AltRight', char: 'Alt', shift: 'Alt'},
    {keycode: 'ControlRight', char: 'Ctrl', shift: 'Ctrl'},
    {keycode: 'ArrowLeft', char: '<-', shift: '<-'},
    {keycode: 'ArrowDown', char: '|', shift: '|'}, 
    {keycode: 'ArrowRight', char: '->', shift: '->'}, ],
]

export let keyboardKeysRussian = [
    [ {keycode: 'Backquote', char: 'ё', shift: 'Ё', alternative: '\~'},
    {keycode: 'Digit1', char: '1', shift: '!'},
    {keycode: 'Digit2', char: '2', shift: '\"\"'},
    {keycode: 'Digit3', char: '3', shift: '№'},
    {keycode: 'Digit4', char: '4', shift: ';'},
    {keycode: 'Digit5', char: '5', shift: '%'},
    {keycode: 'Digit6', char: '6', shift: ':'}, 
    {keycode: 'Digit7', char: '7', shift: '?'}, 
    {keycode: 'Digit8', char: '8', shift: '*'}, 
    {keycode: 'Digit9', char: '9', shift: '('}, 
    {keycode: 'Digit0', char: '0', shift: ')'}, 
    {keycode: 'Minus', char: '-', shift: '_'}, 
    {keycode: 'Equal', char: '=', shift: '+'}, 
    {keycode: 'Backspace', char: 'Backspace', shift: 'Backspace'}, ],
    [ {keycode: 'Tab', char: 'Tab', shift: 'Tab'},
    {keycode: 'KeyQ', char: 'й', shift: 'Й'},
    {keycode: 'KeyW', char: 'ц', shift: 'Ц'},
    {keycode: 'KeyE', char: 'у', shift: 'У'},
    {keycode: 'KeyR', char: 'к', shift: 'К'},
    {keycode: 'KeyT', char: 'е', shift: 'Е'},
    {keycode: 'KeyY', char: 'н', shift: 'Н'},
    {keycode: 'KeyU', char: 'г', shift: 'Г'},
    {keycode: 'KeyI', char: 'ш', shift: 'Ш'},
    {keycode: 'KeyO', char: 'щ', shift: 'Щ'},
    {keycode: 'KeyP', char: 'з', shift: 'З'},
    {keycode: 'BracketLeft', char: 'х', shift: 'Х'},
    {keycode: 'BracketRight', char: 'ъ', shift: 'Ъ'},
    {keycode: 'Backslash', char: '\\', shift: '\/'}, 
    {keycode: 'Delete', char: 'Del', shift: 'Del'},],
    [ {keycode: 'CapsLock', char: 'caps lock', shift: 'caps lock'},
    {keycode: 'KeyA', char: 'ф', shift: 'Ф'},
    {keycode: 'KeyS', char: 'ы', shift: 'Ы'},
    {keycode: 'KeyD', char: 'в', shift: 'В'},
    {keycode: 'KeyF', char: 'а', shift: 'А'},
    {keycode: 'KeyG', char: 'п', shift: 'П'},
    {keycode: 'KeyH', char: 'р', shift: 'Р'}, 
    {keycode: 'KeyJ', char: 'о', shift: 'О'}, 
    {keycode: 'KeyK', char: 'л', shift: 'Л'}, 
    {keycode: 'KeyL', char: 'д', shift: 'Д'}, 
    {keycode: 'Semicolon', char: 'ж', shift: 'Ж'}, 
    {keycode: 'Quote', char: 'э', shift: 'Э'}, 
    {keycode: 'Enter', char: 'enter', shift: 'enter'}, ],
    [ {keycode: 'ShiftLeft', char: 'Shift', shift: 'Shift'},
    {keycode: 'Backslash', char: '\\', shift: '\\'},
    {keycode: 'KeyZ', char: 'я', shift: 'Я'},
    {keycode: 'KeyX', char: 'ч', shift: 'Ч'},
    {keycode: 'KeyC', char: 'с', shift: 'С'},
    {keycode: 'KeyV', char: 'м', shift: 'М'},
    {keycode: 'KeyB', char: 'и', shift: 'И'},
    {keycode: 'KeyN', char: 'т', shift: 'Т'}, 
    {keycode: 'KeyM', char: 'ь', shift: 'Ь'}, 
    {keycode: 'Comma', char: 'б', shift: 'Б'}, 
    {keycode: 'Period', char: 'ю', shift: 'Ю'}, 
    {keycode: 'Slash', char: '.', shift: ','}, 
    {keycode: 'ArrowUp', char: '|', shift: '|'}, 
    {keycode: 'ShiftRight', char: 'Shift', shift: 'Shift'}, ],
    [ {keycode: 'ControlLeft', char: 'Ctrl', shift: 'Ctrl'},
    {keycode: 'MetaLeft', char: 'Win', shift: 'Win'},
    {keycode: 'AltLeft', char: 'Alt', shift: 'Alt'},
    {keycode: 'Space', char: '\ ', shift: '\ '},
    {keycode: 'AltRight', char: 'Alt', shift: 'Alt'},
    {keycode: 'ControlRight', char: 'Ctrl', shift: 'Ctrl'},
    {keycode: 'ArrowLeft', char: '<-', shift: '<-'},
    {keycode: 'ArrowDown', char: '|', shift: '|'}, 
    {keycode: 'ArrowRight', char: '->', shift: '->'}, ],
]